FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install git curl build-essential libclang-dev libtsk-dev -y && \
    ln -s /lib/x86_64-linux-gnu/libtsk.a /lib/x86_64-linux-gnu/liblibtsk.a && \
    ln -s /lib/x86_64-linux-gnu/libtsk.so /lib/x86_64-linux-gnu/liblibtsk.so

RUN curl https://sh.rustup.rs | sh -s -- --default-toolchain nightly -y && \
    . $HOME/.cargo/env

ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /app

CMD ["cargo", "build", "--release"]